### PR TITLE
Comments trigger email to share creator

### PR DESCRIPTION
**Pull request by jackpip**
Triggers emails on comments. Still needs $ heroku addons:create sendgrid:starter

### CODE REVIEW

**Comment by jackpip** [comment]
Looks like I don't have access to the codeship details for this project

**Comment by kenmazaika** [comment]
I'm not sure I have access either.  Let's look into this on the upcoming call.  I'll review the code too, and make a few notes in the meantime.

**Comment by kenmazaika** [comment]
Looks good.  Only suggestion might be to add a test for the mailer action.  See 10.2 here:

http://guides.rubyonrails.org/testing.html#testing-your-mailers

**Comment by kenmazaika** [comment]
@jackpip shoot KristaKarpan in slack a DM with your email address if you want to be added to the CodeShip account so you can explicitly see the messages.  Currently this is the message:

> /home/rof/cache/bundler/ruby/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load': /home/rof/src/github.com/FirehoseCommunity/InnoHack/spec/controllers/shares_controller_spec.rb:113: syntax error, unexpected tIDENTIFIER, expecting '}' (SyntaxError)

Looking at this it looks like it was a problem caused by someone else, but maybe you can help us resolve it.

https://github.com/FirehoseCommunity/InnoHack/blob/master/spec/controllers/shares_controller_spec.rb#L113

That line looks like this:

```
    patch :update, id: share.id, share: {body: "Updated"expect(response).to redirect_to shares_path
```

Which is invalid ruby code.  It should look more like:

```
    patch :update, id: share.id, share: {body: "Updated" }
    expect(response).to redirect_to shares_path
```

Somehow it looks like several characters got deleted somehow.

**Comment by jackpip** [comment]
Please review. I added comment section to share page, emails on comments, and tests for them.

**Comment by kenmazaika** [comment]
Very good work, Jack!  Looks awesome!

**Pull request merged**
