### PR TITLE
added share detail page

### PR DESCRIPTION
**Pull request by kpat108**
Still working on it.  Tests are failing and I am not able to show the title of the share.  It comes up as nil.

### CODE REVIEW

**Comment by kenmazaika** [comment]
Looks solid!  Should I merge this?

**Comment by kpat108** [comment]
I am still trying to figure out why the title is not showing up.

**Comment by kpat108** [comment]
It is good to merge.  All tests are passing as well.

**Comment by kenmazaika** [comment]
Solid!

**Pull request merged**
